#!/usr/bin/env python3

import subprocess
import sys

pkgs = [
    "power-profiles-daemon", "ncdu","kitty", "zsh", "starship", "btop", "fastfetch", "bat", "lsd", "fzf", "zoxide", "duf", "nvim", "lazygit", "lazydocker", "pacman-contrib", "less", "git", "openssh", "nodejs", "npm", "postgresql", "docker","firefox", "nautilus", "gwenview", "okular", "haruna", "elisa", "ttf-fira-sans", "ttf-fira-code", "ttf-firacode-nerd", "ttf-font-awesome", "ttf-cascadia-code-nerd", "stow"]

def run_cmd(cmd, as_sudo=False):
    if as_sudo:
        cmd.insert(0, "sudo")
    
    print(f"\nRunning: {' '.join(cmd)}")
    
    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: Command failed with code {e.returncode}")
        sys.exit(1)
    except FileNotFoundError:
        print(f"ERROR: Command not found: '{cmd[0]}'. Is it installed?")
        sys.exit(1)

def install_pacman_packages():
    print("Installing Pacman packages (requires sudo)")
    cmd = ["pacman", "-S", "--needed", "--noconfirm"] + pkgs
    run_cmd(cmd, as_sudo=True)

def main():
    print("This script will install the necessary dependencies")
    
    try:
        confirm = input("\nContinue? (y/N): ")
    except EOFError:
        sys.exit(1)

    if confirm.lower() != "y":
        print("Installation cancelled.")
        sys.exit(0)
        
    install_pacman_packages()
    
    print("\nInstallation complete.")

if __name__ == "__main__":
    main()