#!/bin/bash

replacement_text=" image"

clear=" Clear"
clipboard_list=$(cliphist list)

chosen=$(echo -e "$clear\n$clipboard_list" | \
        sed "s/\[\[ binary data.*]]/$replacement_text/" | \
        rofi -dmenu -config "$HOME/.config/rofi/themes/clipboard.rasi")

if [[ "$chosen" == "$clear" ]]; then
    cliphist wipe

    notify-send 'Clipboard' 'history cleaned'
elif [[ -n "$chosen" ]]; then
    echo "$chosen" | cliphist decode | wl-copy 

    notify-send 'Clipboard' 'copy to clipboard'
fi