#!/bin/bash
shutdown=""
reboot=""
lock=""
suspend="󰤄"
logout=""

chosen=$(echo "$shutdown
$reboot
$lock
$suspend
$logout" | rofi -dmenu -theme "$HOME/.config/rofi/themes/powermenu.rasi")

case "$chosen" in
    "$shutdown")
        systemctl poweroff ;;
    "$reboot")
        systemctl reboot ;;
    "$lock")
        hyprlock ;;
    "$suspend")
        systemctl suspend ;;
    "$logout")
        hyprctl dispatch exit ;;
    *) exit 1 ;;
esac