[font]
size = 14.0

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[window]
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 7
y = 7

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#0c0c0c"
foreground = "#e5e5e5"

[colors.normal]
black = "#0c0c0c"
red = "#c50f1f"
green = "#19cb00"
yellow = "#c19c00"
blue = "#0D73CC"
magenta = "#881798"
cyan = "#3a96dd"
white = "#cccccc"
