[font]
size = 13.0

[font.normal]
family = "FiraCode"
style = "Regular"

[window]
dimensions = { columns = 100, lines = 40 }
opacity = 0.8
decorations = "none"

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true