[font]
size = 13.0

[font.normal]
family = "FiraCode"
style = "Regular"

[window]
dimensions = { columns = 100, lines = 40 }
opacity = 0.8
decorations = "none"

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Underline"   
blinking = "Always"      


[colors.primary]
background = "#0c0c0c"
foreground = "#e5e5e5"

[colors.normal]
black   = "#0c0c0c"
red     = "#c50f1f"
green   = "#13a10e"
yellow  = "#c19c00"
blue    = "#0037da"
magenta = "#881798"
cyan    = "#3a96dd"
white   = "#cccccc"

[colors.bright]
black   = "#767676"
red     = "#e74856"
green   = "#16c60c"
yellow  = "#f9f1a5"
blue    = "#3b78ff"
magenta = "#b4009e"
cyan    = "#61d6d6"
white   = "#f2f2f2"
