"$schema" = 'https://starship.rs/config-schema.json'
format = """$os$username$hostname$directory$git_branch$character"""
add_newline = false

[os]
format = "[$symbol ]($style)"
style = "bright-blue"
disabled = true

[hostname]
format = "[@$hostname ]($style)"
ssh_only = true
ssh_symbol = " "
style = "bright-black"

[directory]
truncation_symbol = " "
truncation_length = 2
truncate_to_repo = true
style = "blue"
format = "[$path ]($style)"

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"

[git_branch]
symbol = ""
format = "[$symbol $branch ]($style)"
style = "dimmed white"

[cmd_duration]
format = "[ ]($style)"
style = "green"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = "  "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
